# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

board: [ "egokb_control" ]
shield: [ "ego62_dongle", "ego62_left", "ego62_right", "settings_reset" ]

# ---
# include:
#   - board: egokb_control
#     shield: ego62_dongle
#   - board: egokb_control
#     shield: ego62_left
#   - board: egokb_control
#     shield: ego62_right
#   - board: egokb_control
#     shield: settings_reset
