identifier: egokb_control
name: egokb_control
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
  - studio
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
